### ISSUE TITLE
how to set the camera parameters

### ISSUE THREAD

**Issue by kalyo-zjl** [ndrplz/tensorflow_mesh_renderer#1]
Hi, thanks for your demo code.
I may wonder How can I set the camera parameters. I have a set of camera parameters: 
rotation matrix: 3x3
translatioin: 3x1
focal_length: fx, fy
center_point: cx, cy
I can successfully project my 3D vetices to 2D plane using the paramters list above.
But I don't know how to use your renderer with these paramters, what does resolution_px, resolution_mm mean in your code, I can not get desired result if I only set the rotation and translation matrix (4x4) using my camera parameters.

**Comment by ndrplz** [comment]
Hi @kalyo-zjl ,

you can take a look of which is the role of these parameters [here](https://github.com/ndrplz/tensorflow-mesh-renderer/blob/79bec34dcdfad4115e4b833f5d62f9414c5e47a4/rastering/rasterer.py#L48-L61) and [here](https://github.com/ndrplz/tensorflow-mesh-renderer/blob/79bec34dcdfad4115e4b833f5d62f9414c5e47a4/rastering/utils.py#L70-L94).

* You don't need to supply the center point. This is [computed](https://github.com/ndrplz/tensorflow-mesh-renderer/blob/79bec34dcdfad4115e4b833f5d62f9414c5e47a4/rastering/utils.py#L89-L90) as the image center.
* The `resolution_px` is the camera resolution in pixel, i.e. the image you produce will have this resolution. 
* The [`focal_len_mm`](https://github.com/ndrplz/tensorflow-mesh-renderer/blob/79bec34dcdfad4115e4b833f5d62f9414c5e47a4/main.py#L23) is the focal length, expressed in mm of course. While composing the calibration matrix, this is converted to pixels by multiplying it for the [px to mm ratio](https://github.com/ndrplz/tensorflow-mesh-renderer/blob/79bec34dcdfad4115e4b833f5d62f9414c5e47a4/rastering/utils.py#L83-L84). This is why you provide also the sensor resolution in millimeters. In case you already have a focal length expressed in pixels, I guess you can directly inject it in place of [these alphas](https://github.com/ndrplz/tensorflow-mesh-renderer/blob/79bec34dcdfad4115e4b833f5d62f9414c5e47a4/rastering/utils.py#L86-L87).

Best,
Andrea
